### ISSUE TITLE
Add command support to iterm using meta key

### ISSUE THREAD

**Issue by albert-bedrock** [A1Liu/a1liu#23]
https://stackoverflow.com/questions/40990454/how-to-map-mac-command-key-in-vim

Commands:
- Cmd+shift+f find in project
- Cmd+shift+o find file in project

**Comment by A1Liu** [comment]
Meh I will see how MacVim works out. Maybe doing more terminal shit wont be necessary.

**Comment by A1Liu** [comment]
ya no just use the `<Leader` ya doofus
